name: Build and Release

on:
  push:
    tags:
      - "v*"
  workflow_dispatch:

jobs:
  build-windows:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Qt
        uses: jurplel/install-qt-action@v3
        with:
          version: 6.9.0
          modules: qtbase qttools
          cache: true

      - name: Configure CMake
        run: cmake -B build -S . -DCMAKE_PREFIX_PATH=$Env:Qt6_DIR

      - name: Build
        run: cmake --build build --config Release

      - name: Deploy Qt dependencies
        run: |
          $qtBin = "${Env:Qt6_DIR}\bin"
          $exePath = "build\src\Release\TheLastRonin.exe"
          & "$qtBin\windeployqt.exe" --release $exePath

      - name: Create archive
        run: |
          mkdir package
          copy build\src\Release\TheLastRonin.exe package\
          copy build\src\Release\*.dll package\
          tar -czvf TheLastRonin-Windows.zip -C package .

      - name: Upload Release Asset
        uses: softprops/action-gh-release@v1
        with:
          files: TheLastRonin-Windows.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
