name: Build and Release

on:
  push:
    tags:
      - "v*"
  workflow_dispatch:

jobs:
  build-windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install aqtinstall==3.1.*

      - name: Install Qt (MSVC 2019 64-bit)
        run: |
          aqt install-qt windows desktop 6.9.0 win64_msvc2019_64 --outputdir D:\a\TheLastRonin/Qt
          aqt install-tool windows desktop tools_openssl_x64 --outputdir D:\a\TheLastRonin/Qt
          aqt install-tool windows desktop tools_win64_mingw --outputdir D:\a\TheLastRonin/Qt

      - name: Add Qt to PATH
        run: |
          echo "D:\a\TheLastRonin\Qt\6.9.0\msvc2019_64\bin" >> $GITHUB_PATH
          echo "D:\a\TheLastRonin\Qt\Tools\OpenSSL\Win_x64\bin" >> $GITHUB_PATH

      - name: Add MSVC to PATH
        uses: ilammy/msvc-dev-cmd@v1

      - name: Configure and Build
        run: |
          cmake -B build -DCMAKE_BUILD_TYPE=Release -G "Visual Studio 17 2022" -A x64
          cmake --build build --config Release --parallel

      - name: Verify Build
        run: |
          if not exist build\Release\TheLastRonin.exe (exit 1)

      - name: Deploy Qt Dependencies
        run: |
          mkdir deploy
          copy build\Release\TheLastRonin.exe deploy\
          windeployqt.exe --release --no-translations --no-system-d3d-compiler deploy\TheLastRonin.exe

      - name: Create Portable Package
        run: |
          mkdir TheLastRonin-Windows-Portable
          xcopy deploy\* TheLastRonin-Windows-Portable\ /E /I /Y

          echo The Last Ronin - Portable Version > TheLastRonin-Windows-Portable\README.txt
          echo. >> TheLastRonin-Windows-Portable\README.txt
          echo Simply run TheLastRonin.exe to start the application. >> TheLastRonin-Windows-Portable\README.txt
          echo No installation required! >> TheLastRonin-Windows-Portable\README.txt

          powershell Compress-Archive -Path TheLastRonin-Windows-Portable -DestinationPath TheLastRonin-Windows-Portable.zip

      - name: Install Inno Setup
        run: choco install innosetup -y

      - name: Create Windows Installer
        run: |
          & "C:\Program Files (x86)\Inno Setup 6\ISCC.exe" TheLastRonin.iss

      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: windows-releases
          path: |
            TheLastRonin-Windows-Portable.zip
            TheLastRonin-Windows-Setup.exe
