name: Build and Release

on:
  push:
    tags:
      - "v*"
  workflow_dispatch:

env:
  QT_VERSION: 6.7.3
  CMAKE_VERSION: 3.16.3

jobs:
  build-windows:
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install Qt
        uses: jurplel/install-qt-action@v4
        with:
          version: ${{ env.QT_VERSION }}
          host: windows
          target: desktop
          arch: win64_msvc2019_64
          modules: qtmultimedia
          cache: true

      - name: Set up MSVC
        uses: microsoft/setup-msbuild@v2

      - name: Configure CMake
        run: |
          cmake -B build -S . -DCMAKE_BUILD_TYPE=Release -DCMAKE_PREFIX_PATH="${{ env.Qt6_DIR }}"

      - name: Build
        run: |
          cmake --build build --config Release --parallel

      - name: Deploy Qt
        run: |
          mkdir deploy
          copy build\src\Release\TheLastRonin.exe deploy\
          windeployqt.exe --qmldir . --compiler-runtime deploy\TheLastRonin.exe

      - name: Create Windows Archive
        run: |
          cd deploy
          7z a ..\TheLastRonin-Windows-x64.zip *

      - name: Upload Windows Artifact
        uses: actions/upload-artifact@v4
        with:
          name: TheLastRonin-Windows-x64
          path: TheLastRonin-Windows-x64.zip
